name: demandium_serviceman
description: A new Flutter project.

publish_to: 'none' #

version: 1.0.7+9

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.14.12
  shimmer_animation: ^2.2.1
  fl_chart: ^0.68.0
  dotted_border: ^2.1.0
  flutter_local_notifications: ^17.2.1+2
  timelines: ^0.1.0
  file_picker: ^8.0.6
  pdf: ^3.11.0
  open_file_plus: ^3.4.1+1
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  printing: ^5.13.1
  flutter_switch: ^0.3.2
  firebase_crashlytics: ^4.0.3
  photo_view: ^0.15.0
  scroll_to_index: any
  phone_numbers_parser: ^8.3.0
  firebase_auth: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/font/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/Ubuntu-Bold.ttf
          weight: 700
